# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
        runs:
          using: 'node21'

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        
      - name: Cache
        uses: actions/cache@v4.0.2
        
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
            
